spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url : jdbc:mysql://localhost:3306/ProductDb?createDatabaseIfNotExist=true
    username : root
    password :
  jpa :
    hibernate :
      ddl-auto : update
server:
  port: 8080


